kind: pipeline
name: jsonwebtoken-sgx-1604-sw

steps:
- name: sim-compile
  image: baiduxlab/sgx-rust:1604-1.1.3
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - SGX_MODE=SW make -C sgx/jsonwebtoken-sgx-test

- name: sim-test
  image: baiduxlab/sgx-rust:1604-1.1.3
  commands:
  - . /opt/sgxsdk/environment
  - cd sgx/jsonwebtoken-sgx-test/bin && ./app | tee result.txt && grep " 0 failed" result.txt

node:
  instance: sgx

---

kind: pipeline
name: jsonwebtoken-sgx-1604-hw

steps:
- name: hw-compile
  image: baiduxlab/sgx-rust:1604-1.1.3
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - make -C sgx/jsonwebtoken-sgx-test

- name: hw-test
  image: baiduxlab/sgx-rust:1604-1.1.3
  privileged: true
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - ls -l /dev/isgx
  - ls -l /var/run/aesmd/aesm.socket
  - cd sgx/jsonwebtoken-sgx-test/bin && ./app | tee result.txt && grep " 0 failed" result.txt

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx

---

kind: pipeline
name: jsonwebtoken-sgx-1804-sw

steps:
- name: sim-compile
  image: baiduxlab/sgx-rust:1804-1.1.3
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - SGX_MODE=SW make -C sgx/jsonwebtoken-sgx-test

- name: sim-test
  image: baiduxlab/sgx-rust:1804-1.1.3
  commands:
  - . /opt/sgxsdk/environment
  - cd sgx/jsonwebtoken-sgx-test/bin && ./app | tee result.txt && grep " 0 failed" result.txt

node:
  instance: sgx

---

kind: pipeline
name: jsonwebtoken-sgx-1804-hw

steps:
- name: hw-compile
  image: baiduxlab/sgx-rust:1804-1.1.3
  commands:
  - . /opt/sgxsdk/environment
  - . /root/.cargo/env
  - make -C sgx/jsonwebtoken-sgx-test

- name: hw-test
  image: baiduxlab/sgx-rust:1804-1.1.3
  privileged: true
  volumes:
  - name: isgx
    path: /dev/isgx
  - name: aesmd
    path: /var/run/aesmd/aesm.socket
  commands:
  - . /opt/sgxsdk/environment
  - ls -l /dev/isgx
  - ls -l /var/run/aesmd/aesm.socket
  - cd sgx/jsonwebtoken-sgx-test/bin && ./app | tee result.txt && grep " 0 failed" result.txt

volumes:
- name: isgx
  host:
    path: /dev/isgx
- name: aesmd
  host:
    path: /var/run/aesmd/aesm.socket

node:
  instance: sgx
