freebsd_instance:
  image: freebsd-11-2-release-amd64

env:
  RUST_BACKTRACE: full

task:
  name: FreeBSD 11.2 amd64
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
  cargo_cache:
    folder: $HOME/.cargo/registry
  build_script:
    - . $HOME/.cargo/env
    - cargo build
    - cargo build --no-default-features
  amd64_test_script:
    - . $HOME/.cargo/env
    - cargo test
  i386_test_script:
    - . $HOME/.cargo/env
    - rustup target add i686-unknown-freebsd
    - cargo test --target i686-unknown-freebsd
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index
