
# Already done

[dependencies]
rand_core = { path = "/root/sgx/samplecode/teerustpython/already/rand_core" }


mt19937  = { path = "/root/sgx/samplecode/teerustpython/already/mt19937" }
atty = {path = "/root/sgx/samplecode/teerustpython/already/atty"}
ansi_term = {path = "/root/sgx/samplecode/teerustpython/already/ansi_term"}

xxx = {path = "/root/sgx/samplecode/teerustpython/already/xxx"}
# xxx = {path = "/root/sgx/samplecode/teerustpython/already/xxx"}
# xxx = {path = "/root/sgx/samplecode/teerustpython/already/xxx"}
# xxx = {path = "/root/sgx/samplecode/teerustpython/already/xxx"}
# xxx = {path = "/root/sgx/samplecode/teerustpython/already/xxx"}
# xxx = {path = "/root/sgx/samplecode/teerustpython/already/xxx"}
# xxx = {path = "/root/sgx/samplecode/teerustpython/already/xxx"}
# xxx = {path = "/root/sgx/samplecode/teerustpython/already/xxx"}
