[package]
name = "crates-sgx"
version = "0.1.0"
authors = ["Teaclave Contributors"]
edition = "2018"

[dependencies]
# SGX helper
profiler_builtins              = { path = "/root/sgx/samplecode/teerustpython/crate/sgx-fake-profiler-builtins" }

# Rust SGX SDK
sgx_align_struct_attribute     = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_alloc                      = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_backtrace                  = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_backtrace_sys              = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_build_helper               = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_cov                        = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_libc = { path = "/root/sgx/sgx_libc"}
sgx_rand = { path = "/root/sgx/sgx_libc"}
sgx_rand_derive                = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_serialize                  = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_serialize_derive           = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_serialize_derive_internals = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_tcrypto                    = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_tcrypto_helper             = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_tdh                        = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_tkey_exchange              = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_tprotected_fs              = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_trts                       = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_tse                        = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_tseal                      = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_tstd = { path = "/root/sgx/sgx_tstd"}

sgx_tunittest                  = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_types                      = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_unwind                     = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }
sgx_urts                       = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }

# SGX crates
adler32          = { path = "/root/sgx/samplecode/teerustpython/crate/adler32-rs-sgx" }
aho-corasick     = { path = "/root/sgx/samplecode/teerustpython/crate/aho-corasick-sgx" }
anyhow           = { path = "/root/sgx/samplecode/teerustpython/crate/anyhow-sgx" }
array_tool       = { path = "/root/sgx/samplecode/teerustpython/crate/array_tool-sgx" }
base64           = { path = "/root/sgx/samplecode/teerustpython/crate/rust-base64-sgx" }
bincode          = { path = "/root/sgx/samplecode/teerustpython/crate/bincode-sgx" }
byteorder        = { path = "/root/sgx/samplecode/teerustpython/crate/byteorder-sgx" }
bytes            = { path = "/root/sgx/samplecode/teerustpython/crate/bytes-sgx" }
chrono           = { path = "/root/sgx/samplecode/teerustpython/crate/chrono-sgx" }
color_quant      = { path = "/root/sgx/samplecode/teerustpython/crate/color_quant-sgx" }
crc              = { path = "/root/sgx/samplecode/teerustpython/crate/crc-rs-sgx" }
crc32fast        = { path = "/root/sgx/samplecode/teerustpython/crate/rust-crc32fast-sgx" }
deflate          = { path = "/root/sgx/samplecode/teerustpython/crate/deflate-rs-sgx", branch = "dev" }
env_logger       = { path = "/root/sgx/samplecode/teerustpython/crate/env_logger-sgx" }
gbdt             = { path = "/root/sgx/samplecode/teerustpython/crate/gbdt-rs", branch = "mesatee-sgx", features = ["input", "enable_training"] }
getrandom        = { path = "/root/sgx/samplecode/teerustpython/crate/getrandom-sgx" }
gif              = { path = "/root/sgx/samplecode/teerustpython/crate/image-gif-sgx" }
gzip-header      = { path = "/root/sgx/samplecode/teerustpython/crate/gzip-header-sgx" }
heapsize         = { path = "/root/sgx/samplecode/teerustpython/crate/heapsize-sgx" }
hex              = { path = "/root/sgx/samplecode/teerustpython/crate/rust-hex-sgx" }
http             = { path = "/root/sgx/samplecode/teerustpython/crate/http-sgx" }
image            = { path = "/root/sgx/samplecode/teerustpython/crate/image-sgx" }
inflate          = { path = "/root/sgx/samplecode/teerustpython/crate/inflate-sgx" }
integer-encoding = { path = "/root/sgx/samplecode/teerustpython/crate/integer-encoding-rs-sgx" }
iovec            = { path = "/root/sgx/samplecode/teerustpython/crate/iovec-sgx" }
itoa             = { path = "/root/sgx/samplecode/teerustpython/crate/itoa-sgx" }
jpeg-decoder     = { path = "/root/sgx/samplecode/teerustpython/crate/jpeg-decoder-sgx" }
jsonwebtoken     = { path = "/root/sgx/samplecode/teerustpython/crate/jsonwebtoken-sgx" }
linked-hash-map  = { path = "/root/sgx/samplecode/teerustpython/crate/linked-hash-map-sgx" }
log              = { path = "/root/sgx/samplecode/teerustpython/crate/log-sgx" }
lzw              = { path = "/root/sgx/samplecode/teerustpython/crate/lzw-sgx" }
matrixmultiply   = { path = "/root/sgx/samplecode/teerustpython/crate/matrixmultiply-sgx" }
md5              = { path = "/root/sgx/samplecode/teerustpython/crate/md5-sgx" }
mio              = { path = "/root/sgx/samplecode/teerustpython/crate/mio-sgx", tag = "sgx_1.1.3" }
net2             = { path = "/root/sgx/samplecode/teerustpython/crate/net2-rs-sgx" }
num-bigint       = { path = "/root/sgx/samplecode/teerustpython/crate/num-bigint-sgx" }
num-traits       = { path = "/root/sgx/samplecode/teerustpython/crate/num-traits-sgx" }
parity-wasm      = { path = "/root/sgx/samplecode/teerustpython/crate/parity-wasm-sgx" }
percent-encoding = { path = "/root/sgx/samplecode/teerustpython/crate/rust-url-sgx" }
png              = { path = "/root/sgx/samplecode/teerustpython/crate/image-png-sgx" }
prost            = { path = "/root/sgx/samplecode/teerustpython/crate/prost-sgx" }
quick-error      = { path = "/root/sgx/samplecode/teerustpython/crate/quick-error-sgx" }
rand             = { path = "/root/sgx/samplecode/teerustpython/crate/rand-sgx", tag = "v0.7.3_sgx1.1.3" }
rdrand           = { path = "/root/sgx/samplecode/teerustpython/crate/rust_rdrand-sgx" }
regex            = { path = "/root/sgx/samplecode/teerustpython/crate/regex-sgx" }
ring             = { path = "/root/sgx/samplecode/teerustpython/crate/ring-sgx", tag = "v0.16.5" }
rulinalg         = { path = "/root/sgx/samplecode/teerustpython/crate/rulinalg-sgx" }
rustface         = { path = "/root/sgx/samplecode/teerustpython/crate/rustface-sgx" }
rustls           = { path = "/root/sgx/samplecode/teerustpython/crate/rustls", branch = "mesalock_sgx-client-cert-verifier-patch" }
rusty-machine    = { path = "/root/sgx/samplecode/teerustpython/crate/rusty-machine-sgx" }
sct              = { path = "/root/sgx/samplecode/teerustpython/crate/sct.rs", branch = "mesalock_sgx" }
serde            = { path = "/root/sgx/samplecode/teerustpython/crate/serde-sgx-master/serde" }
serde_cbor       = { path = "/root/sgx/samplecode/teerustpython/crate/cbor-sgx" }
serde_derive     = { path = "/root/sgx/samplecode/teerustpython/crate/serde-sgx" }
serde_json       = { path = "/root/sgx/samplecode/teerustpython/crate/serde-json-sgx" }
sha-1            = { path = "/root/sgx/samplecode/teerustpython/crate/hashes-sgx" }
sha1             = { path = "/root/sgx/samplecode/teerustpython/crate/rust-sha1-sgx" }
sha2             = { path = "/root/sgx/samplecode/teerustpython/crate/hashes-sgx" }
snap             = { path = "/root/sgx/samplecode/teerustpython/crate/rust-snappy-sgx" }
thiserror        = { path = "/root/sgx/samplecode/teerustpython/crate/thiserror-sgx" }
threadpool       = { path = "/root/sgx/samplecode/teerustpython/crate/rust-threadpool-sgx" }
tiff             = { path = "/root/sgx/samplecode/teerustpython/crate/image-tiff-sgx" }
toml             = { path = "/root/sgx/samplecode/teerustpython/crate/toml-rs-sgx" }
url              = { path = "/root/sgx/samplecode/teerustpython/crate/rust-url-sgx" }
uuid             = { path = "/root/sgx/samplecode/teerustpython/crate/uuid-sgx" }
wabt             = { path = "/root/sgx/samplecode/teerustpython/crate/wabt-rs-sgx", branch = "v0.9-core" }
wasmi            = { path = "/root/sgx/samplecode/teerustpython/crate/wasmi-sgx" }
webpki           = { path = "/root/sgx/samplecode/teerustpython/crate/webpki", branch = "mesalock_sgx" }
webpki-roots     = { path = "/root/sgx/samplecode/teerustpython/crate/webpki-roots", branch = "mesalock_sgx" }
yasna            = { path = "/root/sgx/samplecode/teerustpython/crate/yasna.rs-sgx" }

# no_std crates
assert_matches = { version = "1.3.0" }
bit-vec        = { version = "0.6.1", default-feature = false }
cfg-if         = "0.1.9"
httparse       = { version = "1.3.4", default-features=false }
itertools      = { version = "0.8.0", default-features = false }
inventory      = { version = "0.1.6" }
lazy_static    = { version = "1.4.0", features = ["spin_no_std"] }
quote          = "0.6"
syn            = "0.15"
untrusted      = { version = "0.7.0" }

[workspace]