[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
num-bigint = { path = "../../..", features = ["serde"] }
serde_test = { path = "/root/sgx/teerustpython/crate/serde-sgx" }
num-integer = { path = "/root/sgx/teerustpython/crate/num-integer-sgx" }
num-traits = { path = "/root/sgx/teerustpython/crate/num-traits-sgx" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "/root/sgx/sgx_types" }
sgx_tstd = { path = "/root/sgx/sgx_tstd" }
sgx_tunittest = {path = "/root/sgx/sgx_tunittest" }
