[package]
name = "blake-hash"
version = "0.3.2"
authors = ["The CryptoCorrosion Contributors"]
license = "MIT/Apache-2.0"
description = "BLAKE hash functions"
repository = "https://github.com/cryptocorrosion/cryptocorrosion"
keywords = ["crypto", "blake", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
block-buffer = { path = "/root/sgx/samplecode/teerustpython/crate/rustcrypto-utils-sgx/block-buffer" }
digest = { path = "/root/sgx/samplecode/teerustpython/crate/rustcrypto-traits-sgx/digest" }
lazy_static = { version = "1.2", features = ["spin_no_std"], optional = true }
simd = { package = "ppv-lite86", path = "/root/sgx/samplecode/teerustpython/crate/cryptocorrosion-sgx/utils-simd/ppv-lite86", version = "0.2.0", optional = true }
sgx_tstd = { path = "/root/sgx/sgx_tstd", optional = true }

[features]
default = ["simd", "mesalock_sgx", "std"]
std = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[dev-dependencies]
#digest = { version = "0.8", features = ["dev"] }

[badges]
travis-ci = { repository = "cryptocorrosion/cryptocorrosion" }
