language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  include:
    # Test nightly feature
    - rust: nightly
      env: NAME="nightly feature"
      script: cargo test --features nightly
    # Test MSRV
    - rust: 1.13.0
      env: NAME="MSRV test"
      script: cargo test --no-default-features --features std
    # Test if crate can be truly built without std
    - env: TARGET=thumbv7em-none-eabi
      script: cargo build --no-default-features --target $TARGET
      install:
        - rustup target add $TARGET

script:
  - cargo test && cargo test --no-default-features &&
    cargo test --no-default-features --features std &&
    cargo test --no-default-features --features "std i128"

notifications:
  slack:
    rooms:
      - dalek-cryptography:Xxv9WotKYWdSoKlgKNqXiHoD#dalek-bots

cache:
  directories:
    - /home/travis/.cargo
