[package]
name = "Validationenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "validationenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
wasmi-validation = { path = "../../../validation" }
parity-wasm = { git = "https://github.com/mesalock-linux/parity-wasm-sgx" }
assert_matches = { git = "https://github.com/mesalock-linux/assert_matches-sgx" }
wabt = { git = "https://github.com/mesalock-linux/wabt-rs-sgx", branch = "v0.9-core" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tunittest = {rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
