[package]
name = "skein-hash"
version = "0.3.0"
authors = ["The CryptoCorrosion Contributors"]
license = "MIT/Apache-2.0"
description = "Skein hash functions"
repository = "https://github.com/cryptocorrosion/hashes"
keywords = ["crypto", "skein", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
block-buffer = { path = "/root/sgx/teerustpython/crate/rustcrypto-utils-sgx" }
block-padding = { path = "/root/sgx/teerustpython/crate/rustcrypto-utils-sgx" }
digest = { path = "/root/sgx/teerustpython/crate/rustcrypto-traits-sgx" }
threefish-cipher = { path = "/root/sgx/teerustpython/crate/cryptocorrosion-sgx" }

[dev-dependencies]
#digest = { version = "0.8", features = ["dev"] }
