[package]
name = "md-5"
version = "0.8.0"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "MD5 hash function"
documentation = "https://docs.rs/md-5"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "md5", "hash", "digest"]
categories = ["cryptography", "no-std"]

[lib]
name = "md5"

[dependencies]
digest = { path = "/root/sgx/teerustpython/crate/rustcrypto-traits-sgx" }
block-buffer = { path = "/root/sgx/teerustpython/crate/rustcrypto-utils-sgx" }
md5-asm = { version = "0.4", optional = true }
opaque-debug = "0.2"
sgx_tstd = { path = "/root/sgx/sgx_tstd", optional = true }

[dev-dependencies]
#digest = { version = "0.8", features = ["dev"] }
#hex-literal = "0.1"

[features]
default = ["std", "mesalock_sgx"]
std = ["digest/std", "mesalock_sgx"]
asm = ["md5-asm"]
mesalock_sgx = ["sgx_tstd"]

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
