[package]
name = "groestl-aesni"
version = "0.2.2"
authors = ["The CryptoCorrosion Contributors"]
license = "MIT/Apache-2.0"
description = "Hardware-accelerated Groestl hash for x86-64 systems with AES extensions"
documentation = "https://docs.rs/groestl-aesni"
keywords = ["crypto", "groestl", "hash", "digest"]
categories = ["cryptography", "no-std"]
repository = "https://github.com/cryptocorrosion/hashes"
edition = "2018"

[dependencies]
block-buffer = { path = "/root/sgx/teerustpython/crate/rustcrypto-utils-sgx" }
digest = { path = "/root/sgx/teerustpython/crate/rustcrypto-traits-sgx" }
lazy_static = { version = "1.2", features = ["spin_no_std"], optional = true }
sgx_tstd = { path = "/root/sgx/sgx_tstd", optional = true }

[dev-dependencies]
#digest = { version = "0.8", features = ["dev"] }

[features]
std = ["sgx_tstd", "lazy_static"]
default = ["mesalock_sgx"]
mesalock_sgx = ["sgx_tstd", "std"]

[badges]
travis-ci = { repository = "cryptocorrosion/cryptocorrosion" }
