[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
bincode = { path = "../../.." }
serde_derive = { path = "/root/sgx/samplecode/teerustpython/crate/serde-sgx" }
#serde_bytes = { path = "/root/sgx/samplecode/teerustpython/crate/serde-bytes-sgx" }
serde = { path = "/root/sgx/samplecode/teerustpython/crate/serde-sgx/serde" }
byteorder = { path = "/root/sgx/samplecode/teerustpython/crate/byteorder-sgx" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "/root/sgx/sgx_types" }
sgx_tstd = { path = "/root/sgx/sgx_tstd" }
sgx_tunittest = {path = "/root/sgx/sgx_tunittest" }
