language: rust
sudo: false

matrix:
  fast_finish: true
  include:

    # Linux
    - rust: nightly
    - rust: beta
    - rust: stable
    - rust: 1.45.0  # = MIN_RUST_VERSION

    # MacOS
    - os: osx
      rust: beta
    - os: osx
      rust: stable

    # Windows
    - os: windows
      rust: beta
    - os: windows
      rust: stable

branches:
  except:
    - staging.tmp
    - trying.tmp

notifications:
  email:
    on_success: never

env:
  global:
    - RUST_BACKTRACE=full

script:
  - cargo build --verbose --workspace
  - cargo doc   --verbose --workspace --no-deps

  - cargo test  --verbose --workspace

  #  unic-ucd-normal is used in unic-ucd with non-default feature
  - cargo test  --verbose --manifest-path unic/ucd/normal/Cargo.toml

  # == Nightly-only ==

  - test "$TRAVIS_RUST_VERSION" != "nightly" ||
    cargo test  --verbose --workspace --all-features

# TODO: - rustdoc --test README.md -L target/debug -L target/debug/deps

# TODO: Enable auto update for gh-pages
#after_success: |
#  cargo doc && \
#  echo '<meta http-equiv="refresh" content="0;url=YOURLIBNAME/index.html">' > target/doc/index.html && \
#  sudo pip install ghp-import && \
#  ghp-import -n target/doc && \
#  git push -qf https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
