[package]
name = "csv-core"
version = "0.1.6"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "Bare bones CSV parsing with no_std support."
documentation = "https://docs.rs/csv-core"
homepage = "https://github.com/BurntSushi/rust-csv"
repository = "https://github.com/BurntSushi/rust-csv"
readme = "README.md"
keywords = ["csv", "comma", "parser", "delimited", "no_std"]
license = "Unlicense/MIT"
categories = ["encoding", "no-std", "parser-implementations"]
workspace = ".."
edition = "2018"

[badges]
travis-ci = { repository = "BurntSushi/rust-csv" }
appveyor = { repository = "BurntSushi/rust-csv" }

[lib]
bench = false

[features]
# default = []
# default = ["libc"]
# libc = ["memchr/libc"]
# libc = [""]
[dependencies]
memchr = { path="/root/sgx/teerustpython/already/memchr-2.3.3", default-features = false }
sgx_tstd                     = { git = "https://github.com/apache/teaclave-sgx-sdk", rev = "v1.1.3" }

# memchr = { version="2.3.0", default-features = false }

[dev-dependencies]
arrayvec = { version = "0.4", default-features = false }
