[package]
name = "memchr"
version = "2.2.1"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>", "bluss"]
description = "Safe interface to memchr."
documentation = "https://docs.rs/memchr/"
homepage = "https://github.com/BurntSushi/rust-memchr"
repository = "https://github.com/BurntSushi/rust-memchr"
readme = "README.md"
keywords = ["memchr", "char", "scan", "strchr", "string"]
license = "Unlicense/MIT"
exclude = ["/ci/*", "/.travis.yml", "/Makefile", "/appveyor.yml", "/sgx/*"]

[badges]
travis-ci = { repository = "BurntSushi/rust-memchr" }
appveyor = { repository = "BurntSushi/rust-memchr" }

[lib]
name = "memchr"
bench = false

[features]
default = ["use_std", "mesalock_sgx"]
use_std = []
mesalock_sgx = ["sgx_tstd", "sgx_libc", "sgx_types"]
libc = ["sgx_libc"]

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_libc = { path = "/root/sgx/sgx_libc", optional = true}
sgx_tstd = { path = "/root/sgx/sgx_tstd", optional = true}
sgx_types = { path = "/root/sgx/sgx_types", optional = true}

[dev-dependencies]
#quickcheck = { version = "0.8", default-features = false }

[profile.test]
opt-level = 3
