[package]
name = "rust2018user"
version = "0.1.0"
authors = ["bluss"]
edition = "2018"
publish = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = { version = "*", path = ".." }
