language: rust

matrix:
  include:
    - rust: 1.36.0
      script:
        - cargo test --verbose
    - rust: nightly
      script:
        - cargo test --verbose
        - cargo test --verbose --no-default-features
        - cargo test --verbose --features "coerce"
        - cargo test --verbose --no-default-features --features "coerce"
