[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
#serde = { path = "/root/sgx/samplecode/teerustpython/crate/serde-sgx", features = ["rc", "unstable"] }
#serde_derive = { path = "/root/sgx/samplecode/teerustpython/crate/serde-sgx" }
#serde_test = { path = "/root/sgx/samplecode/teerustpython/crate/serde-sgx" }
fnv = { path = "/root/sgx/samplecode/teerustpython/crate/rust-fnv-sgx" }
serde = { path = "../../../serde", features = ["rc", "unstable"] }
serde_derive = { path = "../../../serde_derive" }
serde_test = { path = "../../../serde_test" }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "/root/sgx/sgx_types" }
sgx_tstd = { path = "/root/sgx/sgx_tstd" }
sgx_tunittest = { path = "/root/sgx/sgx_tunittest" }
