language: rust
sudo: false
matrix:
  include:
    - rust: stable
    - os: osx

    - env: LIBZ_SYS_STATIC=1
    - env: LIBZ_SYS_STATIC=1
      os: osx

    - rust: stable
      script:
        - cargo generate-lockfile
        - ci/run-docker.sh

    - rust: beta
    - rust: nightly
      before_script:
        - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
      after_success:
        - travis-cargo doc-upload

script:
  - cargo test
  - cargo run --manifest-path systest/Cargo.toml
  - cargo doc --no-deps

notifications:
  email:
    on_success: never
env:
  global:
    secure: "eq1KPWs3sNmvrQj6ayLRrY2Jqwpx4p9CNU5gRU6LCdx2otIQqKXY1Jj9E6uvQIspL6ZpCNzYDMDUSsRdNahdx59WQGD/mxdrFWStUonJ4t0al2FIQ97NaEy57r4vw36oViDCzqZudDlsacHZnpCpI8ei6AB73rGXfxc3g3fxk6o="
