[package]

name = "libz-sys"
version = "1.0.25"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = "z"
build = "build.rs"
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/libz-sys"
documentation = "https://docs.rs/libz-sys"
description = """
Bindings to the system libz library (also known as zlib).
"""
categories = ["external-ffi-bindings"]

[workspace]
members = ["systest"]

[dependencies]
# libc = "0.2.43"
sgx_libc = { path = "/root/sgx/sgx_libc"}
sgx_tstd = { path = "/root/sgx/sgx_tstd"}


[build-dependencies]
pkg-config = "0.3.9"
cc = "1.0.18"

[target.'cfg(target_env = "msvc")'.build-dependencies]
vcpkg = "0.2"

[features]
# When building from source, enable building optimized assembly routines. As
# noted in `contrib/README.contrib`, these routines are experimental and not
# vetted, use at your own risk!
asm = []
# Enable this feature if you want to have a staticly linked libz
static = []
