[package]
name = "sha3"
version = "0.8.2"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "SHA-3 (Keccak) hash function"
documentation = "https://docs.rs/sha3"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "sha3", "keccak", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = { path = "/root/sgx/samplecode/teerustpython/crate/rustcrypto-traits-sgx/digest" }
block-buffer = { path = "/root/sgx/samplecode/teerustpython/crate/rustcrypto-utils-sgx/block-buffer" }
byte-tools = { path = "/root/sgx/samplecode/teerustpython/crate/rustcrypto-utils-sgx/byte-tools" }
opaque-debug = "0.2"
keccak = "0.1"
sgx_tstd = { path = "/root/sgx/sgx_tstd", optional = true }

[dev-dependencies]
#digest = { version = "0.8", features = ["dev"] }
#hex-literal = "0.1"

[features]
default = ["std", "mesalock_sgx"]
std = ["digest/std", "mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
