[package]
name = "sha3"
version = "0.8.2"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "SHA-3 (Keccak) hash function"
documentation = "https://docs.rs/sha3"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "sha3", "keccak", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx" }
block-buffer = { git = "https://github.com/mesalock-linux/rustcrypto-utils-sgx" }
byte-tools = { git = "https://github.com/mesalock-linux/rustcrypto-utils-sgx" }
opaque-debug = "0.2"
keccak = "0.1"
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[dev-dependencies]
#digest = { version = "0.8", features = ["dev"] }
#hex-literal = "0.1"

[features]
default = ["std", "mesalock_sgx"]
std = ["digest/std", "mesalock_sgx"]
mesalock_sgx = ["sgx_tstd"]

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
