[package]
name = "stream-cipher"
version = "0.3.2"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Stream cipher traits"
documentation = "https://docs.rs/stream-cipher"
repository = "https://github.com/RustCrypto/traits"
keywords = ["crypto", "stream-cipher", "trait"]
categories = ["cryptography", "no-std"]

[dependencies]
generic-array = "0.12"
blobby = { path = "/root/sgx/teerustpython/crate/rustcrypto-utils-sgx", optional = true }
sgx_tstd = { path = "/root/sgx/sgx_tstd", optional = true }

[features]
std = ["mesalock_sgx"]
dev = ["blobby"]
mesalock_sgx = ["sgx_tstd"]

[badges]
travis-ci = { repository = "RustCrypto/traits" }

[package.metadata.docs.rs]
features = [ "std" ]
