[package]
name = "Wasmienclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "wasmienclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
wasmi = { path = "../../../" }
wasmi-validation = { path = "../../../validation" }
parity-wasm = { git = "https://github.com/mesalock-linux/parity-wasm-sgx" }
assert_matches = { git = "https://github.com/mesalock-linux/assert_matches-sgx" }
wabt = { git = "https://github.com/mesalock-linux/wabt-rs-sgx", branch = "v0.9-core" }
memory_units = "0.3.0"
rand = { git = "https://github.com/mesalock-linux/rand-sgx", tag = "v0.7.3_sgx1.1.3" }
typetag = { git = "https://github.com/mesalock-linux/typetag-sgx" }
serde = { git = "https://github.com/mesalock-linux/serde-sgx", features = ["derive"] }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tunittest = {rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
