[package]
name = "systest"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"

[dependencies]
libz-sys = { path = ".." }
libc = "0.2"

[build-dependencies]
ctest = "0.1"

[features]
libz-static = ["libz-sys/static"]
