[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
blake-hash = { path = "../../../hashes/blake" }
groestl-aesni = { path = "../../../hashes/groestl" }
jh-x86_64 = { path = "../../../hashes/jh" }
skein-hash = { path = "../../../hashes/skein" }
#crypto-simd = { path = "../../../utils-simd/crypto-simd" }
ppv-lite86 = { path = "../../../utils-simd/ppv-lite86" }
c2-chacha = { path = "../../../stream-ciphers/chacha" }
hex-literal = { path = "/root/sgx/teerustpython/crate/rustcrypto-utils-sgx" }
threefish-cipher = { path = "../../../block-ciphers/threefish" }
block-cipher-trait = { path = "/root/sgx/teerustpython/crate/rustcrypto-traits-sgx" }
digest = { path = "/root/sgx/teerustpython/crate/rustcrypto-traits-sgx", features = ["dev"] }


[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { path = "/root/sgx/sgx_types" }
sgx_tstd = { path = "/root/sgx/sgx_tstd" }
sgx_tunittest = {path = "/root/sgx/sgx_tunittest" }
