[package]
name = "rustpython_freeze"
version = "0.1.2"
authors = ["RustPython Team"]
license = "MIT"
description = "A Python-3 (CPython >= 3.5.0) Interpreter written in Rust, compiled to frozen executable"
repository = "https://github.com/RustPython/RustPython/tree/master/freeze"
edition = "2018"

[[bin]]
name = "rustpython_freeze"
path = "src/main.rs"


[dependencies]
rustpython-vm = { path = "../../vm", default-features = false }
