name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: rustfmt --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust:
          # Our minimal supported version
          - '1.31.0'
          # The standard Rust version
          - stable
          # Future compatibility
          - beta
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      # Run tests with fixed hostname on Unix systems
      - run: sudo hostname hostname-for-testing
        if: "!contains(matrix.os, 'windows')"
      - name: cargo test --ignored
        if: "!contains(matrix.os, 'windows')"
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --ignored
