[package]
name = "blake2"
version = "0.8.1"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "BLAKE2 hash functions"
documentation = "https://docs.rs/blake2"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "blake2", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = { path = "/root/sgx/samplecode/teerustpython/crate/rustcrypto-traits-sgx/digest" }
byte-tools = { path = "/root/sgx/samplecode/teerustpython/crate/rustcrypto-utils-sgx/byte-tools" }
crypto-mac = { path = "/root/sgx/samplecode/teerustpython/crate/rustcrypto-traits-sgx/crypto-mac" }
opaque-debug = "0.2"
sgx_tstd = { path = "/root/sgx/sgx_tstd", optional = true }

[dev-dependencies]
#digest = { version = "0.8", features = ["dev"] }
#crypto-mac = { version = "0.7", features = ["dev"] }
#hex-literal = "0.1"

[features]
default = ["std", "mesalock_sgx"]
std = ["digest/std", "crypto-mac/std", "mesalock_sgx"]
simd = []
simd_opt = ["simd"]
simd_asm = ["simd_opt"]
mesalock_sgx = ["sgx_tstd"]

[badges]
travis-ci = { repository = "RustCrypto/hashes" }
