[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["Baidu"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
yasna = { path = "../../..", features = ["chrono", "bit-vec", "num-bigint"] }
num-traits = { git = "https://github.com/mesalock-linux/num-traits-sgx" }
num-bigint = { git = "https://github.com/mesalock-linux/num-bigint-sgx" }
chrono = { git = "https://github.com/mesalock-linux/chrono-sgx" }
bit-vec = { version = "0.6.1", default-features = false }


[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tstd = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_tunittest = {rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
